[package]
name = "aws-rust"
version = "0.1.0"
authors = ["Roberto Huertas <roberto.huertas@outlook.com>"]
autobins = false

[[bin]]
name = "bootstrap"

[dependencies]
lambda_runtime = "0.1"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
# log = "0.4.6"
# simple_logger = "1.0.1"
